### ISSUE TITLE
Initial release tracker

### ISSUE THREAD

**Issue by felixpalmer** [CartoDB/quadbin-js#3]
## PRs/work remaining

- [x] Initial repo setup @felixpalmer
- [x] Test setup @felixpalmer
- [x] Functions required for deck.gl @felixpalmer
- [x] Functions required for Builder @felixpalmer 
- [ ] Functions required for backend @thedae
- [ ] Tests (to be added with functions)
- [ ] Docs (to be added with functions)

## Integration

- [x] Github repo setup
- [x] Create npm module @felixpalmer
- [x] Deploy to npm script
- [x] CI running tests
